export { default as findFigure } from "./queries/findFigure"
export { default as findPencil } from "./queries/findPencil"
export { default as isCorrectMatch } from "./ruls/isCorrectMatch"
export { default as paintFigure } from "./transformations/paintFigure"
export { default as checkCompleted } from "./transformations/checkCompleted"
export { default as resetSelectedPencil } from "./transformations/resetSelectedPencil"
export { default as checkActivity } from "./transformations/checkActivity"
